# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6b:21:37:64:85:db:df:27:59:1c:0a:19:b8:ee:98:b8"
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:

      - welcome/run
